name: Auto Comment on Closed Issue

# Trigger this action when an issue is closed
on:
  issues:
    types: [closed]

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the closed issue
      uses: peter-evans/issue-commenter@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: |
          Thank you for your contribution! This issue has been closed. If you have further questions, feel free to open a new issue.
