name: Greetings

on:
  pull_request_target:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Send Greeting Message
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
        pr-message: |
          Hi @${{ github.actor }},
          Thanks for opening this PR! We appreciate your contribution and will review it as soon as we can. We’ll get back to you with any feedback or updates shortly.
          Cheers🥂,
